#!/usr/bin/env bash
# ============================================================
# 04-install-dream.sh
# Installs Dream mode: cron-driven reflective memory consolidation.
# Writes ~/.claude/dream.sh wrapper and registers a user cron entry.
# Idempotent.
# ============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "ERROR: $ENV_FILE not found."
  exit 1
fi

# shellcheck disable=SC1090
set -a; source "$ENV_FILE"; set +a

if [[ "${INSTALL_DREAM:-false}" != "true" ]]; then
  echo "==> Dream mode disabled (INSTALL_DREAM != true). Skipping."
  exit 0
fi

export PATH="$HOME/.npm-global/bin:$PATH"

if ! command -v claude >/dev/null 2>&1; then
  echo "ERROR: 'claude' not in PATH. Run 02-install-claude.sh first."
  exit 1
fi

SCHEDULE="${DREAM_SCHEDULE:-0 3 * * *}"
DREAM_DIR="$HOME/.claude"
WRAPPER="$DREAM_DIR/dream.sh"
LOG="$DREAM_DIR/dream.log"
MAX_LOG_BYTES=5242880   # 5 MiB

mkdir -p "$DREAM_DIR"

# Default prompt: try skill first, fall back to inline instructions.
DEFAULT_PROMPT='Invoke the skill `anthropic-skills:consolidate-memory` to perform a reflective pass over ~/.claude/memory/. If the skill is not available, perform the consolidation inline: merge duplicate facts across memory files, fix stale or contradicted entries, delete files that are no longer accurate, and refresh the MEMORY.md index so each line points to a current file. Be conservative — when in doubt, keep the existing memory.'

USER_PROMPT="${DREAM_PROMPT:-$DEFAULT_PROMPT}"

echo "==> Writing wrapper $WRAPPER"
cat > "$WRAPPER" <<EOF
#!/usr/bin/env bash
# Auto-generated by 04-install-dream.sh — do not edit by hand.
# Runs a headless Claude session to consolidate persistent memory.
set -euo pipefail

export PATH="\$HOME/.npm-global/bin:\$PATH"

LOG="$LOG"
MAX=$MAX_LOG_BYTES

# Rotate log if it exceeds MAX bytes (keep tail).
if [[ -f "\$LOG" ]]; then
  size=\$(stat -c%s "\$LOG" 2>/dev/null || stat -f%z "\$LOG" 2>/dev/null || echo 0)
  if (( size > MAX )); then
    tail -c \$(( MAX / 2 )) "\$LOG" > "\$LOG.tmp" && mv "\$LOG.tmp" "\$LOG"
  fi
fi

{
  echo "===== dream start: \$(date -Iseconds) ====="
  claude -p $(printf '%q' "$USER_PROMPT") --dangerously-skip-permissions 2>&1 || \
    echo "dream: claude exited non-zero (\$?)"
  echo "===== dream end:   \$(date -Iseconds) ====="
  echo
} >> "\$LOG"
EOF
chmod 700 "$WRAPPER"

echo "==> Registering user cron entry ($SCHEDULE)"
TMP_CRON="$(mktemp)"
crontab -l 2>/dev/null | grep -v 'claude-dream' > "$TMP_CRON" || true
echo "$SCHEDULE $WRAPPER  # claude-dream" >> "$TMP_CRON"
crontab "$TMP_CRON"
rm -f "$TMP_CRON"

echo
echo "==> Dream mode installed."
echo "    Wrapper: $WRAPPER"
echo "    Log:     $LOG (auto-rotates at 5 MiB)"
echo "    Cron:    $SCHEDULE"
echo
echo "    First-time setup: launch \`claude\` once and run \`/plugin install anthropic-skills\`"
echo "    so the consolidate-memory skill is available. Without it, Dream falls back"
echo "    to an inline reflection prompt."
echo
echo "    Test now:  $WRAPPER && tail -n 40 $LOG"
