#!/usr/bin/env bash
# ============================================================
# lib/mission-control.sh — Mission Control dashboard install.
#
# Upstream: https://github.com/builderz-labs/mission-control
# Runtime: Node.js 22+, pnpm. SQLite (better-sqlite3). Default port 3000.
# Native gateway adapters: OpenClaw, CrewAI, LangGraph, AutoGen, Claude SDK.
# REST API: 101 endpoints documented at /api-docs.
# ============================================================

# Expected env (see each profile's .env.example):
#   INSTALL_MISSION_CONTROL    true/false
#   MC_DIR                     clone destination (default $HOME/mission-control)
#   MC_REPO                    git URL (default upstream)
#   MC_BRANCH                  default main
#   MC_PORT                    HTTP port (default 3000)
#   MC_AS_SERVICE              true → install systemd unit
#   MC_AUTH_USER / MC_AUTH_PASS  admin creds (PASS auto-gen if empty)
#   MC_API_KEY                 headless API key (auto-gen if empty)
#   MC_ALLOWED_HOSTS           comma-separated host allowlist
#   MC_DATA_DIR                data dir (default $HOME/.mission-control)
#   MC_CLAUDE_HOME             default $HOME/.claude
#   OPENCLAW_CONFIG_PATH       default $HOME/.openclaw/openclaw.json
#   OPENCLAW_STATE_DIR         default $HOME/.openclaw

install_mission_control() {
  if [[ "${INSTALL_MISSION_CONTROL:-false}" != "true" ]]; then
    echo "==> Mission Control disabled (INSTALL_MISSION_CONTROL != true)."
    return 0
  fi

  local repo="${MC_REPO:-https://github.com/builderz-labs/mission-control.git}"
  local branch="${MC_BRANCH:-main}"
  local dir="${MC_DIR:-$HOME/mission-control}"
  local data_dir="${MC_DATA_DIR:-$HOME/.mission-control}"

  # Node 22+ is required by Mission Control (Next.js 16 / React 19).
  if command -v install_node >/dev/null 2>&1; then
    install_node 22
  fi
  if command -v install_pnpm >/dev/null 2>&1; then
    install_pnpm latest
  fi

  echo "==> Cloning Mission Control into $dir"
  if [[ -d "$dir/.git" ]]; then
    git -C "$dir" fetch --all --prune
    git -C "$dir" checkout "$branch"
    git -C "$dir" pull --ff-only
  else
    git clone --branch "$branch" "$repo" "$dir"
  fi

  mkdir -p "$data_dir"
  chmod 700 "$data_dir"

  # Auto-generate secrets if operator left them blank.
  local auth_pass="${MC_AUTH_PASS:-$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)}"
  local api_key="${MC_API_KEY:-$(openssl rand -hex 32)}"

  cat > "$dir/.env" <<EOF
# Auto-generated by lib/mission-control.sh — edit then rerun installer to refresh.
PORT=${MC_PORT:-3000}
AUTH_USER=${MC_AUTH_USER:-admin}
AUTH_PASS=${auth_pass}
API_KEY=${api_key}
MC_ALLOWED_HOSTS=${MC_ALLOWED_HOSTS:-}
NEXT_PUBLIC_GATEWAY_OPTIONAL=${MC_GATEWAY_OPTIONAL:-true}
MC_CLAUDE_HOME=${MC_CLAUDE_HOME:-$HOME/.claude}
MISSION_CONTROL_DATA_DIR=${data_dir}
OPENCLAW_CONFIG_PATH=${OPENCLAW_CONFIG_PATH:-$HOME/.openclaw/openclaw.json}
OPENCLAW_STATE_DIR=${OPENCLAW_STATE_DIR:-$HOME/.openclaw}
EOF
  chmod 600 "$dir/.env"

  echo "==> Installing JS deps + building"
  (
    cd "$dir" || exit 1
    pnpm install --frozen-lockfile 2>/dev/null || pnpm install
    pnpm build
  )

  echo
  echo "==> Mission Control built at $dir"
  echo "    Port:       ${MC_PORT:-3000}"
  echo "    Data dir:   $data_dir"
  echo "    .env:       $dir/.env (chmod 600 — contains AUTH_PASS + API_KEY)"
  echo "    First run:  http://localhost:${MC_PORT:-3000}/setup"

  if [[ "${MC_AS_SERVICE:-false}" == "true" ]]; then
    setup_mission_control_systemd "$dir"
  else
    echo "    Manual run: cd $dir && pnpm start"
  fi
}

# Install + enable a systemd unit. Idempotent.
setup_mission_control_systemd() {
  local dir="$1"
  local pnpm_bin
  pnpm_bin="$(command -v pnpm)"

  echo "==> Installing systemd unit (mission-control.service)"
  sudo tee /etc/systemd/system/mission-control.service >/dev/null <<EOF
[Unit]
Description=Mission Control (AI agent orchestration dashboard)
After=network.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$dir
EnvironmentFile=$dir/.env
ExecStart=$pnpm_bin start
Restart=on-failure
RestartSec=5

[Install]
WantedBy=multi-user.target
EOF
  sudo systemctl daemon-reload
  sudo systemctl enable --now mission-control.service
  sudo systemctl --no-pager status mission-control.service || true
}
